version: '3'

services:
    front-nia:
        image: loganlee/front-nia
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 10
        ports:
            - 80:80
        container_name: front
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: local.dockerfile
        environment:
            - CHOKIDAR_USEPOLLING=true
